### ISSUE TITLE
Create New Structure

### ISSUE THREAD

**Issue by darrendbutler** [cmu-variability/pas4aiworkforce#4]
**Description**

The site file should follow a structure similar to the Celebrating Accessibility [course site](https://cmu-05-499.github.io/#weekly-schedule) and [repository.](https://github.com/darrendbutler/cmu-05-499.github.io).

**Scenarios**

The course site should maintain a similar structure for students and faculty navigate the schedule, calendar, and staff information.

![Image](https://github.com/user-attachments/assets/88ce67e4-370a-4939-be0c-b4356e5c1aa1)

**Tasks**

- [ ] Run Celebrating Accessibility Site Locally
- [ ] Move current files to new directory `\old`
- [ ] Copy files from Celebrating Accessibility Site into current repository. 
- [ ] Run new repository.
